image: node:lts

cache:
  key: "$CI_PIPELINE_ID"
  paths:
    - node_modules

stages:
  - prepare
  # - verify
  - build
  - deploy

npm-install:
  stage: prepare
  script:
    - npm install

# .verify:
#   stage: verify
#   script: 
#     - "npm run verify:${BUILD_PLATFORM}"
# verify-ios:
#   tags:
#     - macOS
#     - XCode=13
#   extends: .verify
#   variables:
#     BUILD_PLATFORM: ios
# verify-android:
#   image: containers.l.twogate.net/docker/capacitor-android:sdk30-gradle7
#   extends: .verify
#   variables:
#     BUILD_PLATFORM: android

build-embedded-webview:
  stage: build
  script:
    - npm run build
  only:
    - gitlab/main
    - gitlab/rel/0.0.1
    - tags
  artifacts:
    expire_in: 4h
    paths:
      - dist

build-embedded-webview-controller:
  stage: build
  script:
    - cd ./contentController/ng/
    - npm install
    - npm run build
    - test -e ./dist
  artifacts:
    expire_in: 4h
    paths:
      - contentController/ng/dist


deploy-embedded-webview:
  stage: deploy
  script:
    - npm config set -- '@skomiyama:registry' "https://${CI_SERVER_HOST}/api/v4/projects/1260/packages/npm/"
    - npm config set -- '//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken' "${DEPLOY_TOKEN}"
    - npm config set -- '//${CI_SERVER_HOST}/api/v4/projects/1260/packages/npm/:_authToken' "${DEPLOY_TOKEN}"
    - npm publish
  needs:
    - build-embedded-webview
  only:
    - gitlab/main
    - gitlab/rel/0.0.1
    - tags

deploy-embedded-webview-controller:
  stage: deploy
  script:
    - cd contentController/ng/dist/content-controller/
    - npm config set -- '@skomiyama:registry' "https://${CI_SERVER_HOST}/api/v4/projects/1260/packages/npm/"
    - npm config set -- '//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken' "${DEPLOY_TOKEN}"
    - npm config set -- '//${CI_SERVER_HOST}/api/v4/projects/1260/packages/npm/:_authToken' "${DEPLOY_TOKEN}"
    - npm publish
  needs:
    - build-embedded-webview-controller
  only:
    - gitlab/main
    - gitlab/rel/0.0.1
    - tags
  
