image: node:lts

cache:
  key: "$CI_PIPELINE_ID"
  paths:
    - node_modules

stages:
  - prepare
  # - verify
  - build
  - deploy

npm-install:
  stage: prepare
  script:
    - npm install

# .verify:
#   stage: verify
#   script: 
#     - "npm run verify:${BUILD_PLATFORM}"
# verify-ios:
#   tags:
#     - macOS
#     - XCode=13
#   extends: .verify
#   variables:
#     BUILD_PLATFORM: ios
# verify-android:
#   image: containers.l.twogate.net/docker/capacitor-android:sdk30-gradle7
#   extends: .verify
#   variables:
#     BUILD_PLATFORM: android



build:
  stage: build
  script:
    - npm run build
  only:
    - gitlab/main
    - tags
  artifacts:
    expire_in: 4h
    paths:
      - dist

deploy:
  stage: deploy
  script:
    - npm publish
  only:
    - gitlab/main
    - tags
